### ISSUE TITLE
call event method of parent scope doesn't work in examples/polymer_anchor_point.html

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#10]
In JS this eventmethods (all onclick) are assinged in non-polymer style.
I invented an app-element around the entire content and moved the methods from index.dart to the app-element.
With {{@toggle}} the method in the app-element should be found but doesn't get called.
Investigate if and how this should work or file a bug.

related to #29

**Comment by zoechi** [comment]
still has issues, probably due to polymer-flex-layout issues

**Comment by zoechi** [comment]
use events to propagate changes to the parent element
I had to create an additional element (polymer-flex-area) that can be used instead of div as parent that responds to these events.
http://stackoverflow.com/questions/19977163/how-can-i-access-the-host-of-a-custom-element

**Comment by zoechi** [comment]
still have to track the progress of the {{@xxx}} syntax

**Comment by xxx** [comment]
You rang? :D

**Comment by zoechi** [comment]
took a while until I knew what you meant :D
It was not my intention as I guess you alredy assumed. I hope you don't mind. 
Nice account name.
Have a nice weekend.

**Comment by xxx** [comment]
np ;) it happens a couple times each week.

**Comment by zoechi** [comment]
@ doesn't work this way so the workaround is permanent.
