### ISSUE TITLE
polymer-meta attributes

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#106]
#53

If _metaArray is published through the getter list
- it should be an ObservableMap/List
- the getter list should be notified when the _metaArray is modified

what do you think?

**Comment by ErikGrimes** [comment]
Perhaps give me a chance to respond before committing the changes?  If I understand the code correctly, metaArray is just a lazily initialized list.  It's set once on first access and then never changes. If that's the case, I don't think it makes sense to notify observers; the list never changes from their perspective.

**Comment by zoechi** [comment]
I added some debug output and saw that the it was changed (not the entire list but added elements)

**Comment by zoechi** [comment]
I also already committed the changes but we can of course remove it when it makes no sense.

**Comment by zoechi** [comment]
I assume I can close this one.
