### ISSUE TITLE
Integration of my repo is finished.

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#13]
I'm finished with integrating my code into this repo.
If you don't like anything I have done don't hesitate to tell me.

I think we should publish this new state to pub.dartlang.org.
Please tell me when you are ready for this step.

**Comment by ErikGrimes** [comment]
Cool!

I'd like to fix the following issues first.  That way master is in a good
state.  I'll get started on the today, then you can publish tomorrow?

polymer_elements

#17
#18
#19

polymer_ui_elements

ErikGrimes/polymer_ui_elements#3
ErikGrimes/polymer_ui_elements#4
ErikGrimes/polymer_ui_elements#5

**Comment by ErikGrimes** [comment]
I think we're good to go for a pub update.  You might want to grab the
latest build and double check me.  I ran all the demos and everything
appears to be in order.
