### ISSUE TITLE
firing a CustomEvent in Polymer gives me “Exception: Class 'xxx' has no instance method '[]'”

### ISSUE THREAD

**Issue by MikeMitterer** [bwu-dart-graveyard/polymer_elements#143]
Please refer to http://stackoverflow.com/questions/22962543/firing-a-customevent-in-polymer-gives-me-exception-class-mydata-has-no-insta/22985672#22985672

It is not possible to fire a Dart-Object because PolymerSignals wants a name and data property for this object in registerListener:
https://github.com/ErikGrimes/polymer_elements/blob/master/lib/polymer_signals/polymer_signals.dart

Workaround:
asyncFire('polymer-signal',detail: { 'name' : "mydata", 'data' : new MyData("Mike",47) });

**Possible solution for "name"**
var data =  new MyData("Mike",47);
final String name = reflect(data).type.reflectedType.toString().toLowerCase();

**Comment by zoechi** [comment]
Hi Mike,
thanks for the report and the workaround.
I took a look at the JavaScript polymer-signals and it has the same code.

I'll think about if your proposed change makes sense.
You would have to create a class for each event.

Maybe an additional type check can satisfy both variants.

```
if(e.detail is Map) {
  if(!(e.detail as Map).containsKey('name') {
    throw some_better_error_message
  }
 ... current behavior
} else {
  ... your proposal
}
```

**Comment by MikeMitterer** [comment]
Hi Günter, I really appreciate your help - thx!

I think your suggestion is the way to go.

**Comment by zoechi** [comment]
I committed a little different solution to avoid using reflection. I hope this is fine for you.
A type used as detail has to implement EventNameProvider (`import 'packages:polymer_elements/src/interfaces.dart'`)
