### ISSUE TITLE
polymer_overlay.html uses polymer-key-helper Tag but this tag is commented out in polymer_elements.dart

### ISSUE THREAD

**Issue by MikeMitterer** [bwu-dart-graveyard/polymer_elements#145]
Here is the overlay.html which is using the key-helper:
https://github.com/ErikGrimes/polymer_elements/blob/master/lib/polymer_overlay/polymer_overlay.html

And here is polymer_elements.dart: 
https://github.com/ErikGrimes/polymer_elements/blob/master/lib/polymer_elements.dart

**Comment by zoechi** [comment]
Hi Mike,

thanks for the hint!
KeyHelper redundant to me because Dart has constant definitions for keycodes already included. I'll remove the tag which doesn't do anything in polymer-overlay.
