### ISSUE TITLE
document the directory structure (what to put where, naming conventions) in a wiki page

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#16]

**Comment by zoechi** [comment]
created a skeleton page

**Comment by zoechi** [comment]
I filled the skeleton:
[Code conventsion](https://github.com/ErikGrimes/polymer_elements/wiki/Code-conventions)
It would be nice if you could proof read the document and fix or add as you want.
My English is in need for improvement, so corrections or suggestions are welcome. 
If you find it sufficient please close this issue

**Comment by ErikGrimes** [comment]
Sure.  Where can I find it?

**Comment by zoechi** [comment]
https://github.com/ErikGrimes/polymer_elements/wiki/Code-conventions
I already had added the link in the previous comment (Code conventions).
Was the link not included in your notification message?

**Comment by ErikGrimes** [comment]
It got stripped out, but I see it now.  I'll have a look and close the
issue when I'm done.

**Comment by ErikGrimes** [comment]
I think it captures the rules we're following well enough, which is all we really need. So, looks good to me!
