### ISSUE TITLE
implement directory conventions

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_elements#17]
Here's the convention I'd like to follow using polymer-ajax as an example.  Note the use of underscores everywhere.  

example/polymer_ajax/index.html
example/polymer/ajax/ajax_example.html
example/polymer/ajax_example.dart

lib/polymer_ajax
lib/polymer_ajax/polymer ajax related files

**Comment by zoechi** [comment]
I would prefer to have a subdirectory for each component in example as well
I thought it would better fit the Dart package layout convention to have the entry point in example (like in web) and supporting files in src (and subdirs in src to keep it neat).
If it works with all tools I'm fine with this approach.

lib is fine as well.

**Comment by ErikGrimes** [comment]
I was looking at the polymer.js convention and thought it would be nice if example mirrored lib.  The tools are pretty much a crapshoot at this point.  I can't debug polymer-ajax from it's demo for example.  I went ahead and mirrored your directory structure and naming scheme.  We can always revisit the convention. It's just important we have one :)

**Comment by zoechi** [comment]
I also have regularily problems getting the debugger stopping at
breakpoints.
What almost always works is the debugger integrated in Dartium devtools.

I like the current directory structure. If it's also fine with you we
leave it until someone (important ;-) ) tells us to change it.

**Comment by ErikGrimes** [comment]
Agreed.
