### ISSUE TITLE
move experimental elements into separate branches

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_elements#19]
Move any element that doesn't pass the "demo" test into a separate branch.

**Comment by zoechi** [comment]
I thought this would be a good practice as well.
The problem are the depenencies.
I started with one element and the associated example page, then I created the elements the demo page depends on up to a state that the element I tried to convert and it's example page worked without errors.

If I move those dummy elements out I have to delete depending code and reintroduce this later.
This seems a lot of work.
I would rather accept that not all code in master can be used and maintain the readme.

If you have concerns I try to follow your guideline.

**Comment by zoechi** [comment]
I thought more about your request.
I dislike to much buggy unfinished code in master either.

What do you think about keeping all in master until the project itself is out of experimental.
I find it to bothersome just for now.

**Comment by zoechi** [comment]
please move this issue to later if you agree
