### ISSUE TITLE
distinct subdirectory for each element

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#2]
As a wrote in PM we should decide if we create a distinct subdirectory for each component as in the JS repo.
I am in favor of subdirectories because some elements have several additional files (css, svg, png, ...) so the lib directory gets a bit messy if all files are in the same directory. 
It is also not ease to see which file belongs to which component.

A disadvantage is the longer import path for the component user.
What do you think?

**Comment by ErikGrimes** [comment]
I prefer distinct subdirectories.  I did this because of issues with debugging in the editor.  I think everything is in the right place now.

**Comment by zoechi** [comment]
yeah, looks good.
