### ISSUE TITLE
Remove dash from event name

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#24]
warning lib/polymer_selector/polymer_selector.html:13:57: Invalid event name "on-polymer-select". After the "on-" the event name should not use dashes. For example use "on-polymerSelect" or "on-polymerselect" (both forms are equivalent in HTML).
    <polymer-selection id="selection" multi="{{multi}}" on-polymer-select="{{selectionSelect}}"></polymer-selection>
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by ErikGrimes** [comment]
Dart's custom event matching is case sensitive (see https://code.google.com/p/dart/issues/detail?id=14719).  Going  with all lowercase event names for now (e.g. 'polymerselect').  It makes them hard to read though.
