### ISSUE TITLE
port polymer-overlay

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_elements#32]
Port polymer-overlay (https://github.com/Polymer/polymer-elements/tree/master/polymer-overlay).

**Comment by ghost** [comment]
Hi, great works. I would like to contribute something for the porting works.

I'm porting polymer_overlay polymer_ui_overlay experimentally, still not work and have local commits (not pushing yet).
https://github.com/ntaoo/polymer_ui_overlay_dart
Of cause it does not mean any obstacle to your work and schedule, It's just info.
