### ISSUE TITLE
selection_example problems

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#36]
selection_example.dart
- [x] enteredView() needs super() call
- [x] enteredView() should have @override annotation
- [x] leftView() needs super call and @override
- [ ] itemTapAction() shows warning The method 'select' is not defined for the class 'Element'

I consider it good practice to call super on all overridden methods (xxxChanged are no overrides though, they are called using reflection as I understand it)
@override annotation is controversial even inside the Dart team (couln't find the recent discussion)
But as I understand it, it should be used when overriding methods from packages which are maintained by someone else.

**Comment by ErikGrimes** [comment]
Created this [issus](https://github.com/ErikGrimes/polymer_elements/issues/42) for itemTapAction.

**Comment by zoechi** [comment]
Should be possible to link to other issues with just a hash and the number #42.
github recognizes such links and has support in some views (just read it lately, never used it myself yet).
Has even intellisense available for this kind of links - great.
