### ISSUE TITLE
What is the Dart upgrade policy

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#4]
I normally upgrade to a new Dart SDK/editor from 
http://gsdview.appspot.com/dart-editor-archive-trunk/latest
as soon as the updated packages are available on pub.dartlang.org.

We need to adjust here because otherwise we would break the code for each other
and it is necessary to update pubspec.yaml accordingly before publishing a package.

(I published to pub.dartlang.org every time when I fixed the code for a new SDK version or after a new working component was added)

I have an upgrade script which checks if a new Dart version is available, downloads and installs it (for Linux). If you are interested just send a note.

**Comment by ErikGrimes** [comment]
My only thing is master should always be in a working state.  As long as
we're not working off master, that is we each create working branches and
merge to master, we should be fine.  When a new sdk release hits, we create
an issue, create a port branch, port and merge the work back in when it's
complete.   Also, this way when anything hits master, you know it's save to
push it to pub.

Erik

**Comment by ErikGrimes** [comment]
Would you send me your upgrade script? I'm on a mac, but I'd love to take a
look. Also, any ideas what's different between the link your using and the
latest continuous one listed on the official editor page (
https://storage.googleapis.com/dart-editor-archive-continuous/latest/)?

**Comment by zoechi** [comment]
ok (SDK release)
I didn't realize there are other URLs. This would be interesting to know what the difference is.

**Comment by ErikGrimes** [comment]
I grabbed a build of 0.8.9 (
http://gsdview.appspot.com/dart-editor-archive-continuous/29720/) and
rolled both projects to 0.8.9 with it. I updated the readmes to include the
build used. The continuous build is a moving target.  We might not be
working on the same build otherwise. I like the goal of keeping our pub
releases in line with polymer releases.  We can roll master once a week to
the next upcoming release and do our push to pub after it's complete. The
alternative is we work with current stable release and lag behind a few
days. What do you think?

On Thu, Oct 31, 2013 at 12:08 PM, Günter Zöchbauer <notifications@github.com

**Comment by zoechi** [comment]
Hi Erik,

I strive to go with the latest release.
The last months I had to halt work on some projects many times because
of blocking Dart bugs.
As soon as a new release is available it check if more things are
working yet.
Of course there are often new bugs in new releases but I'm definitely in
favor of new bugs than old ones ;-)

Somewhat annoying is that drone.io is often some days behind and the
badge in the README.md goes to red until they upgrade.
But I think this is acceptable when working with projects that are so
much in flux.
After the massive amount of breaking changes in Polymer I think they
will slow down a little to stabilize for 1.0.

Günter

**Comment by ErikGrimes** [comment]
I understand the frustration of being blocked by dart bugs.  I also understand the frustration of continuously upgrading to the latest sdk and having previously working things break. It's a balancing act. If you upgrade the build your developing with and want merge to master, please do the following:

1) Update the link in the readme to the build master is now targeting
2) Check the demos and update the status of any existing 'ported' elements that are affected by the change. Automated tests will eventually make this unnecessary.

**Comment by zoechi** [comment]
The breaking changes come anyways so I don't bother much.

1), 2) understood
