### ISSUE TITLE
library statement

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#41]
I wonder about your library statement in the dart code files.

I just used the element name as library name because the library name doesn't really matter in polymer-element files (AFAIK) it's just that there should be one, otherwise there are some issues in some situations (build, ...?).

I went for the shortest name that seemed reasonable to me.
If you attach some importance to have also the package name in the library statement I'm fine with that.
But then it should be polymer_elements/polymer_ui_elements instead of polymer.elements/polymer.ui_elements

Please let me know what was your reasoning behind this decision?

**Comment by ErikGrimes** [comment]
I originally thought polymer_elements/polymer_ui_elements would be part of
polymer. I'm not sure why. It was a brave new world. So I chose
package.subpackage.library with a bit of shortening for convenience.
 Polymer uses package.library.  Let's follow that convention.  That would
make the the library name for polymer_ajax.dart
'polymer_elements.polymer_ajax'. The only question is, what do we do for
helper libs?

**Comment by zoechi** [comment]
Do you have an example what you mean with helper libs.
If it's something we haven't yet in the project we can decide when we have such a case.
