### ISSUE TITLE
Use classes instead of maps for custom event details

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_elements#45]
Polymer.js polymer-elements uses maps for passing information in custom event detail.  This is less than ideal.  It doesn't play well with binding expressions or editor features such as autocompletion.

**Comment by zoechi** [comment]
+1

**Comment by ErikGrimes** [comment]
Hmm.  Why was this closed? Reopening until we actually replace the maps with classes.

**Comment by zoechi** [comment]
sorry my bad. was not my intention.
Thanks for reopening.
