### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#5]
I extended the README.md and added a table with all components (polymer_elements and polymer_ui_elements) where we can show the progress (which components are ported)
For "status" I used
- "not ported" nothing done yet
- "started" porting started but nothing useful available yet
- "ported" porting is done, 
  I added <strong>name</strong> for elements that are really working
  I added a comment when an element is ported but does not working properly yet (i.e. because of missing Dart features or open Dart bugs)

I left "not started" for all elements not ported by me. Please update the files according to your progress.

(I have not yet committed/pushed - in case you read this before I'm done with integrating my code in this repository)

**Comment by ErikGrimes** [comment]
Done
