### ISSUE TITLE
MediaQuery not yet supported in Dart

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/polymer_elements#60]
I tried to finish polymer-ui-toolbar but it depends on polymer-media-query which again is blocked by the following issues:
- [html/dom: MediaQueryList and MediaQueryListListener](https://code.google.com/p/dart/issues/detail?id=3338)
- [Dartify media queries](https://code.google.com/p/dart/issues/detail?id=9233)

related to #52

JS based workaround [“matchMedia” support in Dart](http://stackoverflow.com/questions/19745361/matchmedia-support-in-dart)

**Comment by ErikGrimes** [comment]
I've starred them.  Does that close this issue?

**Comment by zoechi** [comment]
I reopen this issue to have the dependency visible and change the title.
