### ISSUE TITLE
polymer-selector throws Uncaught DataCloneError: An object could not be cloned

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_elements#61]
polymer-selector throws 'Uncaught DataCloneError: An object could not be cloned'.

**Comment by ErikGrimes** [comment]
Waiting on feedback on [this thread](https://groups.google.com/a/dartlang.org/forum/#!topic/web-ui/UKhjAwAKEkw).

**Comment by zoechi** [comment]
Should be fixed [Uncaught Error: DataCloneError](https://code.google.com/p/dart/issues/detail?id=14779)

**Comment by zoechi** [comment]
Couldn't reproduce
