### ISSUE TITLE
Remove dependency on polymer-ui-elements

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_elements#64]
I'm not sure why the dependency is there, but circular dependencies are a pretty bad code smell.

**Comment by zoechi** [comment]
I thought I already replied to this ... 

In principle I agree 100%.

But in polymer-elements only the examples depend on polymer-ui-elements.
We could move the examples out of the package but I consider it documentation and would not want to split implementation and docs.
Should there arise a dependency from a custom element in polymer-elements to polymer-ui-elements I would consider this an error.

polymer-ui-elements depend heavily on polymer-elements but that is fine.

Another solution would be to pack all elements in one package. 
But as long that custom elements in polymer-elements don't rely on polymer-ui-elements I find this a good abstraction which I would not remove.

What do you think?

**Comment by ErikGrimes** [comment]
I like having the examples with the package.  Let's leave things as they
are.
