### ISSUE TITLE
support EventStreamProviders for custom elements

### ISSUE THREAD

**Issue by ErikGrimes** [bwu-dart-graveyard/polymer_elements#80]
There's a pattern of for events in the html package that uses EventStreamProvider.  Should we support this?

**Comment by zoechi** [comment]
I find it very convenient to have a method with autocompletion instead of an string that I have to find first in source code or documentation to be able to subscribe to the event.
All HTML elements have their events exposed as methods onXXX in Dart why should custom elements not have them?

**Comment by ErikGrimes** [comment]
There's no reason per se, it's just different than the polymer.js version.  I've avoided straying too far from polymer.js to date.  In the past, I've provided event streams with my custom elements.  I like the consistency with the html elements and how it makes the events a custom element generates both explicit and easy to find.
